#!/bin/bash

# =====================================================
# environmental variables for central-env.common
# =====================================================
source ../Environmental_Variables/.env.common

echo ""
echo "##############################################################"
echo "Build three bitnami/kafka:2.8 :"
echo ""
rm -rf kafka
rm -rf log

docker rm -f kafka-1
docker rm -f kafka-2
docker rm -f kafka-3

mkdir -p ./kafka/log
mkdir -p ./kafka/broker1/data
mkdir -p ./kafka/broker2/data
mkdir -p ./kafka/broker3/data

chmod 777 -R ./kafka

# 分割zookeeper port
IFS=',' read -r TOPIC_MGT_ZOOKEEPER_PORT1 TOPIC_MGT_ZOOKEEPER_PORT2 TOPIC_MGT_ZOOKEEPER_PORT3 <<< "$TOPIC_MGT_ZOOKEEPER_PORT"

# 分割KAFKA port
IFS=',' read -r TOPIC_MGT_KAFKA_PORT1 TOPIC_MGT_KAFKA_PORT2 TOPIC_MGT_KAFKA_PORT3 <<< "$TOPIC_MGT_KAFKA_PORT"

docker run -d \
--name kafka-1 \
-p ${TOPIC_MGT_KAFKA_PORT1}:9092 \
-v $PWD/kafka/broker1/data:/bitnami/kafka/data \
-v $PWD/kafka/log:/log/ \
-e KAFKA_CFG_ZOOKEEPER_CONNECT="${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_ZOOKEEPER_PORT1},${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_ZOOKEEPER_PORT2},${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_ZOOKEEPER_PORT3}" \
-e KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=18000 \
-e KAFKA_CFG_LISTENERS="PLAINTEXT://:9092" \
-e KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_KAFKA_PORT1}" \
-e KAFKA_CFG_NUM_NETWORK_THREADS=3 \
-e KAFKA_CFG_NUM_IO_THREADS=8 \
-e KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES=102400 \
-e KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=102400 \
-e KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=104857600 \
-e KAFKA_CFG_LOG_DIRS="/bitnami/kafka/data" \
-e KAFKA_CFG_NUM_PARTITIONS=1 \
-e KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR=1 \
-e KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
-e KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
-e KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1 \
-e KAFKA_CFG_LOG_RETENTION_HOURS=168 \
-e KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824 \
-e KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=300000 \
-e KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE="false" \
-e ALLOW_PLAINTEXT_LISTENER="yes" \
--restart always \
bitnamilegacy/kafka:2.8.1

docker run -d \
--name kafka-2 \
-p ${TOPIC_MGT_KAFKA_PORT2}:9092 \
-v $PWD/kafka/broker2/data:/bitnami/kafka/data \
-v $PWD/kafka/log:/log/ \
-e KAFKA_CFG_ZOOKEEPER_CONNECT="${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_ZOOKEEPER_PORT1},${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_ZOOKEEPER_PORT2},${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_ZOOKEEPER_PORT3}" \
-e KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=18000 \
-e KAFKA_CFG_LISTENERS="PLAINTEXT://:9092" \
-e KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_KAFKA_PORT2}" \
-e KAFKA_CFG_NUM_NETWORK_THREADS=3 \
-e KAFKA_CFG_NUM_IO_THREADS=8 \
-e KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES=102400 \
-e KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=102400 \
-e KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=104857600 \
-e KAFKA_CFG_LOG_DIRS="/bitnami/kafka/data" \
-e KAFKA_CFG_NUM_PARTITIONS=1 \
-e KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR=1 \
-e KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
-e KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
-e KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1 \
-e KAFKA_CFG_LOG_RETENTION_HOURS=168 \
-e KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824 \
-e KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=300000 \
-e KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE="false" \
-e ALLOW_PLAINTEXT_LISTENER="yes" \
--restart always \
bitnamilegacy/kafka:2.8.1

docker run -d \
--name kafka-3 \
-p ${TOPIC_MGT_KAFKA_PORT3}:9092 \
-v $PWD/kafka/broker3/data:/bitnami/kafka/data \
-v $PWD/kafka/log:/log/ \
-e KAFKA_CFG_ZOOKEEPER_CONNECT="${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_ZOOKEEPER_PORT1},${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_ZOOKEEPER_PORT2},${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_ZOOKEEPER_PORT3}" \
-e KAFKA_CFG_ZOOKEEPER_CONNECTION_TIMEOUT_MS=18000 \
-e KAFKA_CFG_LISTENERS="PLAINTEXT://:9092" \
-e KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://${TOPIC_MGT_KAFKA_EXTERNAL_IP}:${TOPIC_MGT_KAFKA_PORT3}" \
-e KAFKA_CFG_NUM_NETWORK_THREADS=3 \
-e KAFKA_CFG_NUM_IO_THREADS=8 \
-e KAFKA_CFG_SOCKET_SEND_BUFFER_BYTES=102400 \
-e KAFKA_CFG_SOCKET_RECEIVE_BUFFER_BYTES=102400 \
-e KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=104857600 \
-e KAFKA_CFG_LOG_DIRS="/bitnami/kafka/data" \
-e KAFKA_CFG_NUM_PARTITIONS=1 \
-e KAFKA_CFG_NUM_RECOVERY_THREADS_PER_DATA_DIR=1 \
-e KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
-e KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
-e KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1 \
-e KAFKA_CFG_LOG_RETENTION_HOURS=168 \
-e KAFKA_CFG_LOG_SEGMENT_BYTES=1073741824 \
-e KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=300000 \
-e KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE="false" \
-e ALLOW_PLAINTEXT_LISTENER="yes" \
--restart always \
bitnamilegacy/kafka:2.8.1
echo "##############################################################"
